title:             Developer's notebook
email:             haaawk@gmail.com
description:       Notes from my everyday work
author:            Piotr Jastrzębski
baseurl:           ""
url:               "http://haaawk.github.io"

# Social Profiles
github_username:   haaawk

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
